- name: create user ansible
  user:
      name: ansible
      groups: root

  
- name: add ssh key for user ansible
  authorized_key:
            user: ansible
            key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILMnkp0wVuNi7UvddFM1Ru4mmOKy77pEczLA+wHebMnn ansible key" 

- name: add sudoers file for user ansible
  copy:
        src: sudoers_ansible
        dest: /etc/sudoers.d/ansible
        owner: root
        group: root
        mode: 0440

