apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-opendistro-pv
spec:
  storageClassName: elasticsearch-opendistro-volume
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/elasticsearch-opendistro"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-opendistro
  namespace: elasticsearch-opendistro
spec:
  selector:
    matchLabels:
      app: elasticsearch-opendistro
  serviceName: elasticsearch-opendistro
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch-opendistro
    spec:
      containers:
        - name: elasticsearch-opendistro
          image: amazon/opendistro-for-elasticsearch:1.13.0
          env:
            - name: discovery.type
              value: single-node
            - name: NETWORK_HOST
              value: "0.0.0.0"
            - name: TRANSPORT_TLS_PEM_PASS
              value: "passphrase"
            - name: HTTP_TLS_PEM_PASS
              value: "passphrase"
          ports:
            - containerPort: 9200
              name: http
              protocol: TCP
            - containerPort: 9300
              name: nodes
              protocol: TCP
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-opendistro-volume-claim
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: elasticsearch-opendistro-volume
        resources:
          requests:
            storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-opendistro
  namespace: elasticsearch-opendistro
spec:
  type: NodePort
  selector:
    app: elasticsearch-opendistro
  ports:
    - name: http
      port: 9200
      protocol: TCP
    - name: nodes
      port: 9300
      protocol: TCP
