---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-opendistro-configmap
  namespace: elasticsearch-opendistro
  labels:
    app: kibana-opendsitro-configmap
data:
  kibana.yml: |-
    ---
    server.name: kibana
    server.host: "0"
    elasticsearch.hosts: https://elasticsearch-opendistro:9200
    elasticsearch.requestTimeout: 360000
    elasticsearch.ssl.verificationMode: none
    elasticsearch.username: admin
    elasticsearch.password: admin
    #elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]
    #
    opendistro_security.multitenancy.enabled: true
    opendistro_security.multitenancy.tenants.preferred: ["Private", "Global"]
    opendistro_security.readonly_mode.roles: ["kibana_read_only"]

    #server.ssl.enabled: true
    #server.ssl.key: /usr/share/kibana/config/kibana-key.pem
    #server.ssl.certificate: /usr/share/kibana/config/kibana-crt.pem
    #server.ssl.keyPassphrase: ${KEY_PASSPHRASE}
    #elasticsearch.ssl.certificateAuthorities: /usr/share/kibana/config/kibana-root-ca.pem
    #opendistro_security.cookie.secure: true
    #opendistro_security.cookie.password: ${COOKIE_PASS}
    
    #User this setting if you are running kibana without https
    opendistro_security.cookie.secure: false

    newsfeed.enabled: false
    telemetry.optIn: false
    telemetry.enabled: false
