apiVersion: v1
kind: PersistentVolume
metadata:
        name: elasticsearch-pv
spec:
        storageClassName: elasticsearch-volume
        capacity:
                storage: 1Gi
        accessModes:
                - ReadWriteOnce 
        hostPath:
                path: "/mnt/elasticsearch"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: elasticsearch
    namespace: elasticsearch
spec:
    selector:
        matchLabels:
            app: elasticsearch
    serviceName: elasticsearch
    replicas: 1
    template:
        metadata:
            labels:
               app: elasticsearch
        spec:
            containers:
               - name: elasticsearch
                 image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
                 env:
                 - name: discovery.type
                   value: single-node
                 ports:
                 - containerPort: 9200
                   name: http
                   protocol: TCP
                 - containerPort: 9300
                   name: nodes
                   protocol: TCP
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-volume-claim
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: elasticsearch-volume
        resources:
            requests:
               storage: 1Gi        

---

apiVersion: v1
kind: Service
metadata:
   name: elasticsearch
   namespace: elasticsearch
spec:
   type: NodePort
   selector:
       app: elasticsearch
   ports:
       - name: http
         port: 9200
         protocol: TCP
       - name: nodes
         port: 9300
         protocol: TCP

