- name: add kubernetes repository
  apt:
     name: apt-transport-https
     state: latest


- name: install containerd runtime
  apt:
     name: containerd
     state: latest


- name: add kubernetes key
  apt_key:
     url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
     state: present


- name: add kubernetes repository
  apt_repository:
     repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
     state: present
     filename: kubernetes


- name: update source list
  apt:
     update_cache: yes


- name: install vim git curl wget kubelet kubeadm kubectl
  apt:
     name:
         - vim
         - git
         - curl
         - wget
         - kubelet
         - kubeadm
         - kubectl
     


- name: enable and start kubelet service
  systemd:
      name: kubelet
      enabled: yes
      state: started



- name: load netfilter module
  copy:
      src: netfilter.conf
      dest: /etc/modules-load.d/k8s.conf
      owner: root
      group: root
      mode: 0644


- name: do sudo modeprobe br_netfilter
  modprobe:
      name: br_netfilter
      state: present


- name: do sudo modprobe overlay
  modprobe:
      name: overlay
      state: present

 
- name: configure bridged traffic
  copy:
      src: bridge.conf
      dest: /etc/sysctl.d/k8s.conf
      owner: root
      group: root
      mode: 0644
      

- name: do sudo sysctl --system
  become: true
  become_user: root
  shell: sysctl --system
